<a href="https://colab.research.google.com/github/kri-pa08/Credit-Risk-Model-Development-and-Validation-/blob/main/credit_risk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    "Age": [25, 45, 32, 51, 28, 40, 35, 52, 30, 48],
    "Income": [30000, 80000, 35000, 90000, 40000, 70000, 45000, 95000, 38000, 85000],
    "LoanAmount": [500000, 300000, 700000, 250000, 600000, 350000, 650000, 200000, 550000, 280000],
    "CreditScore": [650, 750, 580, 780, 620, 720, 590, 800, 630, 760],
    "PreviousDefault": [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    "Default": [0, 0, 1, 0, 1, 0, 1, 0, 1, 0]
}
df = pd.DataFrame(data)

In [ ]:
df.head()

   Age  Income  LoanAmount  CreditScore  PreviousDefault  Default
0   25   30000      500000          650                0        0
1   45   80000      300000          750                0        0
2   32   35000      700000          580                1        1
3   51   90000      250000          780                0        0
4   28   40000      600000          620                1        1

In [ ]:
df.head()

   Age  Income  LoanAmount  CreditScore  PreviousDefault  Default
0   25   30000      500000          650                0        0
1   45   80000      300000          750                0        0
2   32   35000      700000          580                1        1
3   51   90000      250000          780                0        0
4   28   40000      600000          620                1        1

In [ ]:
df.shape

(10, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              10 non-null     int64
 1   Income           10 non-null     int64
 2   LoanAmount       10 non-null     int64
 3   CreditScore      10 non-null     int64
 4   PreviousDefault  10 non-null     int64
 5   Default          10 non-null     int64
dtypes: int64(6)
memory usage: 612.0 bytes

In [ ]:
df.describe()

,Age,Income,LoanAmount,CreditScore,PreviousDefault,Default
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,38.600000,60800.000000,438000.000000,688.000000,0.400000,0.400000
std,9.957688,25555.169079,182562.013817,82.838531,0.516398,0.516398
min,25.000000,30000.000000,200000.000000,580.000000,0.000000,0.000000
25%,30.500000,38500.000000,285000.000000,622.500000,0.000000,0.000000
50%,37.500000,57500.000000,425000.000000,685.000000,0.000000,0.000000
75%,47.250000,83750.000000,587500.000000,757.500000,1.000000,1.000000
max,52.000000,95000.000000,700000.000000,800.000000,1.000000,1.000000

In [ ]:
df.isnull().sum()

Age                0
Income             0
LoanAmount         0
CreditScore        0
PreviousDefault    0
Default            0
dtype: int64

In [ ]:
X = df.drop("Default", axis=1)
y = df["Default"]

In [ ]:
X.head()

   Age  Income  LoanAmount  CreditScore  PreviousDefault
0   25   30000      500000          650                0
1   45   80000      300000          750                0
2   32   35000      700000          580                1
3   51   90000      250000          780                0
4   28   40000      600000          620                1

In [ ]:
y.head()

0    0
1    0
2    1
3    0
4    1
Name: Default, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [ ]:
model.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

NameError: name 'train_test_split' is not defined

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8, 5), (2, 5), (8,), (2,))

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [ ]:
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([0, 1])

In [ ]:
X_test

   Age  Income  LoanAmount  CreditScore  PreviousDefault
5   40   70000      350000          720                0
2   32   35000      700000          580                1

In [ ]:
y_test

5    0
2    1
Name: Default, dtype: int64

In [ ]:
y.pred

AttributeError: 'Series' object has no attribute 'pred'

In [ ]:
y_pred

array([0, 1])

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

1.0

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1 0]
 [0 1]]

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

In [ ]:
new_customer = [[30, 40000, 600000, 610, 1]]

prediction = model.predict(new_customer)

print(prediction)

[1]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [ ]:
model.predict_proba(new_customer)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[7.57093930e-08, 9.99999924e-01]])